# Generated by Django 4.0.3 on 2022-03-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipe', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='detail',
        ),
    ]
