# Generated by Django 4.0.3 on 2022-03-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipe', '0004_remove_material_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sauce',
            name='detail',
        ),
    ]
