# Generated by Django 4.0.3 on 2022-03-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipe', '0005_remove_sauce_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/userupload'),
        ),
    ]
