# Generated by Django 4.0.3 on 2022-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipe', '0007_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
