# Generated by Django 4.0.3 on 2022-03-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipe', '0008_recipe_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='RecipeImage',
        ),
        migrations.AddField(
            model_name='recipe',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/userupload'),
        ),
    ]
