# Generated by Django 4.0.3 on 2022-04-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipe', '0010_alter_recipe_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
