# Generated by Django 4.0.3 on 2022-04-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipe', '0011_alter_recipe_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sauce',
            name='unit',
        ),
    ]
