# Generated by Django 4.0.3 on 2022-05-01 14:42

from django.db import migrations, models
import myRecipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipe', '0012_remove_sauce_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to="images/userupload"),
        ),
    ]
